"""
Gradio UI for FinAgent-Rec
Interactive interface for financial product recommendations
"""

import gradio as gr
import sys
import os

# Add src to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from ontology import initialize_ontology
from vector_store import initialize_vector_store
from agents import create_orchestrator, RecommendationRequest


class FinAgentInterface:
    """
    Gradio interface for FinAgent-Rec system
    """
    
    def __init__(self):
        # Initialize components
        print("Initializing FinAgent-Rec system...")
        self.ontology = initialize_ontology()
        self.vector_store = initialize_vector_store()
        self.orchestrator = create_orchestrator(self.ontology, self.vector_store)
        print("System ready!")
    
    def get_recommendation(self, risk_level: str, additional_criteria: str) -> str:
        """
        Get recommendation based on user input
        
        Args:
            risk_level: Selected risk level (Low, Medium, High)
            additional_criteria: User's additional criteria/description
            
        Returns:
            Formatted recommendation text
        """
        # Create recommendation request
        request = RecommendationRequest(
            user_id="user_session",
            risk_profile=risk_level,
            description=additional_criteria if additional_criteria else "Looking for suitable investments",
            num_recommendations=3
        )
        
        # Get recommendations from orchestrator
        recommendations = self.orchestrator.get_recommendations(request)
        
        if not recommendations:
            return "No suitable recommendations found. Please adjust your criteria."
        
        # Format results
        result = f"<div style='font-family: Arial, sans-serif; max-width: 900px;'>"
        result += f"<h2>Personalized Financial Recommendations</h2>"
        result += f"<p><strong>Your Risk Profile:</strong> {risk_level}</p>"
        result += f"<hr style='margin: 20px 0;'>"
        
        for idx, rec in enumerate(recommendations, 1):
            result += f"<div style='margin: 20px 0; padding: 15px; border: 1px solid #ddd; border-radius: 5px;'>"
            result += f"<h3>#{idx} {rec.product_name}</h3>"
            
            # Score section
            result += f"<div style='margin: 15px 0; background-color: #f9f9f9; padding: 10px; border-radius: 3px;'>"
            result += f"<strong>Recommendation Scores:</strong><br>"
            result += f"<ul style='margin: 10px 0;'>"
            result += f"<li><strong>Overall Score:</strong> {rec.overall_score:.1%}</li>"
            result += f"<li><strong>Vector Similarity:</strong> {rec.vector_similarity:.1%}</li>"
            result += f"<li><strong>Graph Consistency:</strong> {rec.graph_consistency:.1%}</li>"
            result += f"</ul>"
            result += f"</div>"
            
            # Risk level
            result += f"<p><strong>Risk Level:</strong> <span style='color: {'red' if rec.risk_level == 'High' else 'orange' if rec.risk_level == 'Medium' else 'green'};'>{rec.risk_level}</span></p>"
            
            # Explanation
            result += f"<p><strong>Explanation:</strong></p>"
            result += f"<p style='line-height: 1.6; color: #333;'>{rec.explanation}</p>"
            
            # Justification
            result += f"<details style='margin-top: 10px;'>"
            result += f"<summary style='cursor: pointer; color: #0066cc;'><strong>View Ontology Justification</strong></summary>"
            result += f"<div style='margin-top: 10px; padding: 10px; background-color: #f0f0f0; border-left: 3px solid #0066cc;'>"
            result += f"<p><strong>RDF Triples:</strong></p>"
            result += f"<ul style='font-family: monospace; font-size: 12px;'>"
            for triple in rec.justification.get("ontology_triples", []):
                if triple:
                    result += f"<li>{triple}</li>"
            result += f"</ul>"
            
            result += f"<p><strong>Matching Criteria:</strong></p>"
            result += f"<ul style='font-size: 12px;'>"
            for criterion, description in rec.justification.get("matching_criteria", {}).items():
                result += f"<li><strong>{criterion.replace('_', ' ').title()}:</strong> {description}</li>"
            result += f"</ul>"
            result += f"</div>"
            result += f"</details>"
            
            result += f"</div>"
        
        result += f"<hr style='margin: 20px 0;'>"
        result += f"<p style='font-size: 12px; color: #666;'>"
        result += f"<strong>Note:</strong> These recommendations are generated by analyzing your risk profile against our knowledge graph and semantic search. "
        result += f"They are for informational purposes and should not be considered as financial advice. "
        result += f"Please consult with a financial advisor before making investment decisions."
        result += f"</p>"
        result += f"</div>"
        
        return result
    
    def create_interface(self) -> gr.Blocks:
        """
        Create the Gradio interface
        """
        with gr.Blocks(
            title="FinAgent-Rec: AI-Powered Financial Recommendations",
            theme=gr.themes.Soft(),
            css="""
                .container { max-width: 1000px; margin: auto; }
                .header { text-align: center; margin: 30px 0; }
            """
        ) as demo:
            with gr.Group(elem_classes=["container"]):
                with gr.Group(elem_classes=["header"]):
                    gr.Markdown(
                        """
                        # 🏦 FinAgent-Rec
                        ### AI-Powered Multi-Agent RAG System for Financial Recommendations
                        
                        This system uses a Knowledge Graph, Vector Embeddings, and Multi-Agent reasoning to provide explainable financial product recommendations tailored to your risk profile.
                        """
                    )
                
                with gr.Group():
                    gr.Markdown("## 📊 Your Investment Profile")
                    
                    with gr.Row():
                        risk_level = gr.Radio(
                            choices=["Low", "Medium", "High"],
                            value="Medium",
                            label="Risk Profile",
                            info="Select your investment risk tolerance"
                        )
                    
                    with gr.Row():
                        additional_criteria = gr.Textbox(
                            label="Additional Criteria (Optional)",
                            placeholder="E.g., 'I prefer liquid assets with dividend income' or 'I'm looking for growth potential'",
                            lines=3,
                            info="Describe any specific preferences or constraints"
                        )
                
                with gr.Group():
                    gr.Markdown("## 🎯 Personalized Recommendations")
                    
                    output = gr.HTML(
                        label="Recommendations",
                        value="<p>Click 'Get Recommendations' to receive personalized financial product suggestions.</p>"
                    )
                    
                    get_button = gr.Button(
                        "🚀 Get Recommendations",
                        variant="primary",
                        size="lg"
                    )
                
                with gr.Group():
                    gr.Markdown("## ℹ️ How It Works")
                    gr.Markdown(
                        """
                        **FinAgent-Rec** uses a sophisticated multi-agent system:
                        
                        1. **Retrieval Agent** 🔍: Fetches products from both the RDF Knowledge Graph and Vector Store
                        2. **Risk Alignment Agent** ✓: Validates products against your risk profile using ontology rules
                        3. **Reasoning Agent** 💡: Generates natural language explanations citing specific knowledge graph relationships
                        
                        The final recommendation score combines:
                        - **Vector Similarity** (30%): Semantic relevance to your description
                        - **Graph Consistency** (70%): Alignment with your risk profile in the knowledge graph
                        
                        This ensures recommendations are both relevant AND safe.
                        """
                    )
            
            # Set button click handler
            get_button.click(
                fn=self.get_recommendation,
                inputs=[risk_level, additional_criteria],
                outputs=output
            )
        
        return demo


def main():
    """
    Main function to launch the Gradio interface
    """
    interface = FinAgentInterface()
    demo = interface.create_interface()
    
    # Launch the app
    demo.launch(
        server_name="0.0.0.0",
        server_port=7860,
        share=False,
        show_error=True
    )


if __name__ == "__main__":
    main()
